### ISSUE TITLE
lyra2rev2 not working(apply property undefined)

### ISSUE THREAD

**Issue by yuhki0513** [foxer666/node-stratum-pool#5]
Hello. now i try this project code from foxer666 nomp
thanks for your currently update!

now I get error from nomp-log.
lyra2rev2 algo no have apply properties.

please tell me workagrouds.
```
/habitat/nomp/node_modules/stratum-pool/lib/algoProperties.js:119
                return multiHashing.lyra2rev2.apply(this, arguments);
                                             ^

TypeError: Cannot read property 'apply' of undefined
    at /habitat/nomp/node_modules/stratum-pool/lib/algoProperties.js:119:46
    at JobManager.processShare (/habitat/nomp/node_modules/stratum-pool/lib/jobManager.js:224:26)
    at StratumClient.<anonymous> (/habitat/nomp/node_modules/stratum-pool/lib/pool.js:495:46)
    at emitTwo (events.js:130:20)
    at StratumClient.emit (events.js:213:7)
    at handleSubmit (/habitat/nomp/node_modules/stratum-pool/lib/stratum.js:175:15)
    at handleMessage (/habitat/nomp/node_modules/stratum-pool/lib/stratum.js:88:17)
    at /habitat/nomp/node_modules/stratum-pool/lib/stratum.js:248:25
    at Array.forEach (native)
    at Socket.<anonymous> (/habitat/nomp/node_modules/stratum-pool/lib/stratum.js:234:26)
```

**Comment by foxer666** [comment]
@yuhki0513 
Try now )

**Comment by devnull-ed** [comment]
Is problem resolved? Check recent master
